- name: "Install apache2"
  apt: 
    name: apache2
    state: present 
    update_cache: yes
  become: true
  tags:
    - apache

- name: "Install certbot"
  apt: 
    name: certbot
    state: present 
    update_cache: yes
  become: true
  tags:
    - apache
    - certbot

- name: "Install openssl"
  apt: 
    name: openssl
    state: present 
    update_cache: yes
  become: true
  tags:
    - apache
    - openssl

#- name: "Configure Secure ciphers"
  #lineinfile: 
    #path: /etc/apache2/mod-available
    #regexp: "^SSLCipher"
    #line: "  SSLCipherSuite \"EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+AESGCM EECDH EDH+AESGCM EDH+aRSA HIGH !MEDIUM !LOW !aNULL !eNULL !LOW !RC4 !MD5 !EXP !PSK !SRP !DSS !DES !3DES\""
    #handler: apache-restart