
- name: "Add Repo: DBeaver"
  apt_repository: 
    repo: ppa:serge-rider/dbeaver-ce
    state: present
  become: true

- name: "Install DBeaver"
  apt: 
    name: dbeaver-ce
    state: present 
    update_cache: yes
  become: true

