- name: "Install dependencies for Docker"
  apt:
    name:
      - ca-certificates
      - gnupg
    state: present
  become: true
  tags:
    - docker

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
  become: true
  tags:
    - docker

- name: "Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true
  tags:
    - docker

- name: "Update apt cache"
  apt:
    update_cache: yes
  become: true
  tags:
    - docker

- name: "Install Docker packages"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  tags:
    - docker

- name: "Add user to docker group"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  tags:
    - docker
