- name: "Install flatpak and flatpakhub"
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags: flatpak

- name: "Install packages that are installed via flatpak"
  community.general.flatpak: 
    name:
      - io.dbeaver.DBeaverCommunity
      - org.clementine_player.Clementine
      - org.kde.kruler
      - com.github.vkohaupt.vokoscreenNG
      - net.lutris.Lutris
      - com.jgraph.drawio.desktop 

    state: present
    method: user
  tags: flatpak
