- name: "Install packages that are installed via flatpak"
  community.general.flatpak: 
    name:
      - com.calibre_ebook.calibre
      - io.dbeaver.DBeaverCommunity
      - io.github.mimbrero.WhatsAppDesktop
      - org.audacityteam.Audacity
      - org.clementine_player.Clementine
      - com.play0ad.zeroad
      - org.keepassxc.KeePassXC
      - org.kde.kruler
      - fr.natron.Natron
      - org.musicbrainz.Picard
      - com.getpostman.Postman
      - com.sweethome3d.Sweethome3d
      - com.github.vkohaupt.vokoscreenNG
      - com.logseq.Logseq
      - com.jgraph.drawio.desktop 
      - com.spotify.Client
      - org.audacityteam.Audacity
      - org.telegram.desktop
      - com.uploadedlobster.peek
    state: present
    method: user
  tags: flatpak
