- name: "Add GitHub CLI GPG key"
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
  become: true
  tags:
    - github-cli
    - gh

- name: "Add GitHub CLI repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    filename: github-cli
  become: true
  tags:
    - github-cli
    - gh

- name: "Install GitHub CLI"
  apt:
    name: gh
    state: present
    update_cache: yes
  become: true
  tags:
    - github-cli
    - gh
