- name: "Install dependencies for Helm"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true
  tags:
    - helm
    - kubernetes

- name: "Add Helm GPG key"
  ansible.builtin.shell: |
    curl -fsSL https://baltocdn.com/helm/signing.asc | gpg --dearmor -o /etc/apt/keyrings/helm.gpg
  args:
    creates: /etc/apt/keyrings/helm.gpg
  become: true
  tags:
    - helm
    - kubernetes

- name: "Add Helm apt repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian
  become: true
  tags:
    - helm
    - kubernetes

- name: "Install Helm"
  apt:
    name: helm
    state: present
    update_cache: yes
  become: true
  tags:
    - helm
    - kubernetes
