- name: "Add GnuPG and Repo: Keepassxc"
  apt_repository: 
    repo: ppa:phoerious/keepassxc
    state: present
  become: true
  tags:
    - keepassxc
    - keepassxc-repo

- name: "Install keepassxc"
  apt: 
    name: keepassxc
    state: present 
    update_cache: yes
  become: true
  tags: keepassxc

