- name: "Add GnuPG key - Kubectl."
  tags: 
    - google-key
    - kubectl
  block:
    - name: Kubectl | no apt key
      ansible.builtin.shell: 'curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'
        
    - name: Kubectl | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes.list
  become: true

- name: "Install kubectl"
  ansible.builtin.apt: 
    name: kubectl
    state: present 
    update_cache: yes
  become: true
  tags: kubectl

