
- name: "Add Repo: Lutris"
  apt_repository: 
    repo: ppa:lutris-team/lutris
    state: present
  become: true
  tags: 
    - lutris-repo
    - lutris

- name: "Install lutris"
  apt: 
    name: lutris
    state: present 
    update_cache: yes
  become: true
  tags: lutris

