- name: "Add GnuPG key: MEGA"
  apt_key:
    url: https://mega.nz/linux/MEGAsync/xUbuntu_19.04/Release.key
    state: present

- name: "Add Repo: MEGAsync"
  apt_repository:
    repo: deb https://mega.nz/linux/MEGAsync/xUbuntu_19.04/ ./
    state: present
    filename: 'megasync'

- name: "Install megasync"
  apt: 
    name: megasync
    state: present 
    update_cache: yes

