- name: "Add GnuPG key: MEGA"
  tags:
    - mega
    - mega-keys
  block:
    - name: mega | no apt key
      ansible.builtin.get_url:
        url: https://mega.nz/linux/repo/xUbuntu_22.04/Release.key
        dest: /etc/apt/trusted.gpg.d/mega.asc

    - name: mega | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/mega.asc] https://mega.nz/linux/repo/xUbuntu_22.04/ ./"
        state: present
  become: true

- name: "Install megasync"
  apt: 
    deb: https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megasync-xUbuntu_22.04_amd64.deb
    state: present 
    update_cache: yes
  ignore_errors: true
  become: true
  tags:
    - mega

