- name: "Add GnuPG key: MEGA"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BF8B66E01192CBA2E72201294B4E7A9523ACD201

- name: "Add Repo: MEGAsync"
  apt_repository:
    repo: deb https://mega.nz/linux/MEGAsync/xUbuntu_17.10/ ./
    state: present
    filename: 'megasync'

- name: "Install megasync"
  apt: 
    name: megasync
    state: installed 
    update_cache: yes

