- name: "Add GnuPG key - Microsoft."
  apt_key:
    url: https://https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: "Add Repo: VSCode"
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: 'vscode'

- name: "Add Repo: Teams"
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/ms-teams stable main
    state: present
    filename: 'teams'

- name: "Install vscode"
  apt: 
    name: vscode
    state: present 
    update_cache: yes

- name: "Install teams"
  apt: 
    name: teams
    state: present 
    update_cache: yes

