- name: "Add GnuPG key - Microsoft."
  tags:
    - microsoft 
    - microsoft-repo
    - vscode
    - edge
  block:
    - name: Microsoft |no apt key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/trusted.gpg.d/microsoft.asc

    - name: Microsoft | apt source vscode
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] http://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Microsoft | apt source edge
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] http://packages.microsoft.com/repos/edge stable main"
        state: present             
  become: true

- name: "Install vscode (code)"
  apt: 
    name: code
    state: present 
    update_cache: yes
  become: true
  tags:
    - microsoft
    - vscode

- name: "Install edge"
  apt: 
    name: microsoft-edge-stable
    state: present 
    update_cache: yes
  become: true
  tags:
    - microsoft
    - edge
