- name: "Add GnuPG key - Multisystem."
  tags: 
    - multisystem
    - multisystem-key
  block:
    - name: multisystem |no apt key
      ansible.builtin.get_url:
        url: http://liveusb.info/multisystem/depot/multisystem.asc
        dest: /etc/apt/trusted.gpg.d/multisystem.asc

    - name: multisystem | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/multisystem.asc] http://liveusb.info/multisystem/depot all main"
        state: present
  become: true

- name: "Install multisystem"
  apt: 
    name: multisystem
    state: present 
    update_cache: yes
  become: true
  tags: multisystem

