- name: "Add GnuPG key - openfortivpn."
  block:
    - name: openfortivpn |no apt key
      ansible.builtin.shell: 'gpg -k && gpg --no-default-keyring --keyring /usr/share/keyrings/iteas-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 23CAE45582EB0928'

    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/iteas-keyring.gpg] https://apt.iteas.at/iteas noble main"
        state: present
  become: true
  tags:
    - openfortivpn

- name: "Install openfortivpn"
  apt: 
    name: openfortigui
    state: present
    update_cache: yes
  become: true
  tags:
    - openfortivpn  

