- name: "Add GnuPG key: Skype."
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    state: present

- name: "Add Repo: Skype"
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    state: present
    filename: 'skype-stable'

- name: "Install skypeforlinux"
  apt: 
    name: skypeforlinux
    state: installed 
    update_cache: yes

