- name: "Setup ssh handler so we can open ssh:// links in chrome"
  copy:
    src: "../files/ssh.desktop"
    dest: "/home/pbulteel/.local/share/applicatiions/ssh.desktop"

- name: "Setup xdg-mime handler"
  shell: "xdg-mime default ssh.desktop x-scheme-handler/ssh" 
