- name: "Add GnuPG key: Steam."
  apt_key:
    url: https://repo.steampowered.com/steam/archive/stable/steam.gpg
    state: present

- name: "Add Repo: Steam"
  apt_repository:
    repo: deb [arch=amd64,i386] http://repo.steampowered.com/steam/ stable steam
    state: present
    filename: 'steam'

- name: "Add Repo: Steam src"
  apt_repository:
    repo: deb-src [arch=amd64,i386] http://repo.steampowered.com/steam/ stable steam
    state: present
    filename: 'steam'

- name: "Install steam"
  package: 
    name: 
     - libgl1-mesa-dri:amd64
     - libgl1-mesa-dri:i386
     - libgl1-mesa-glx:amd64
     - libgl1-mesa-glx:i386
     - steam-launcher
    state: present 
    update_cache: yes
    

