- name: "Add GnuPG key: Steam."
  block:
    - name: steam |no apt key
      ansible.builtin.get_url:
        url: https://repo.steampowered.com/steam/archive/stable/steam.gpg
        dest: /etc/apt/trusted.gpg.d/steam.asc

    - name: steam | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,i386 signed-by=/etc/apt/trusted.gpg.d/steam.asc] http://repo.steampowered.com/steam/ stable steam"
        state: present

    - name: steam src | apt source
      ansible.builtin.apt_repository:
        repo: "deb-src [arch=amd64,i386 signed-by=/etc/apt/trusted.gpg.d/steam.asc] http://repo.steampowered.com/steam/ stable steam"
        state: present
  become: true

- name: "Install steam"
  package: 
    name: 
     - libgl1-mesa-dri:amd64
     - libgl1-mesa-dri:i386
     - libgl1-mesa-glx:amd64
     - libgl1-mesa-glx:i386
     - steam-launcher
    state: present 
    update_cache: yes
  become: true
    

