- name: "Add Repo: Tilix"
  apt_repository:
    repo: ppa:webupd8team/terminix
    state: present
    filename: 'webupd8team-ubuntu-terminix'
  become: true
  tags: tilix

- name: "Install tilix"
  apt: 
    name: tilix
    state: present 
    update_cache: yes
  become: true
  tags: tilix

