- name: "Add Repo: uget Integrator"
  apt_repository:
    repo: ppa:uget-team/ppa
    state: present
    filename: 'uget-integrator'
  become: true
  tags: uget

- name: "Install uget integrator"
  apt: 
    name: uget-integrator
    state: present 
    update_cache: yes
  become: true
  tags: uget

- name: "Install uget"
  apt: 
    name: uget
    state: present 
  become: true
  tags: uget
