- name: "Add GnuPG key: zoom."
  ansible.builtin.get_url:
    url: https://zoom.us/linux/download/pubkey
    dest: /usr/share/keyrings/zoom.gpg
  become: true

- name: "Install zoom"
  apt: 
    deb: https://zoom.us/client/latest/zoom_amd64.deb
    state: present 
    update_cache: yes
  become: true

